language: php
cache:
  bundler: true
  apt: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$HOME/.npm"
php:
  - 5.5
  
sudo: false

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version

install:
  - export PATH="$HOME/.composer/vendor/bin:$TRAVIS_BUILD_DIR/bin:$PATH"

  - export COMPOSER_EXIT_ON_PATCH_FAILURE=1

  - mysql -e 'SET GLOBAL wait_timeout = 5400;'
  - mysql -e "SHOW VARIABLES LIKE 'wait_timeout'"

  # PHP Configurations.
  - echo 'max_execution_time = 300' >> drupal.php.ini;
  - echo 'max_input_time = 180' >> drupal.php.ini;
  - echo 'max_input_vars = 10000' >> drupal.php.ini;
  - echo 'memory_limit = 512M' >> drupal.php.ini;
  - echo 'error_reporting = E_ALL' >> drupal.php.ini;
  - echo 'post_max_size = 64M' >> drupal.php.ini;
  - echo 'upload_max_filesize = 32M' >> drupal.php.ini;
  - echo 'max_file_uploads = 40' >> drupal.php.ini;
  - echo 'sendmail_path = /bin/true' >> drupal.php.ini;
  - phpenv config-add drupal.php.ini
  - phpenv rehash
  
  - composer install
  - bin/behat --init
  


script:
  - bin/behat features

matrix:
  fast_finish: true
